// src/constants/dbSchema.js

export const TABLES = {
  VENDORS: "vendor_request",
  USER: "user",
  DELIVERY_ADDRESS: "delivery_address",
  CUSION_CATEGORY: "cuisine_category",
  USER_SEARCHES:"user_searches",
  ORDERS: 'orders',
  RATING: 'rating',
  TRANSACTION: 'transaction',
  ORDER_ITEM: 'order_item',
  CART_ITEM: 'cart_item',
  USER_CART: 'user_cart',
  SELECTED_ADDRESS: 'selected_address',
  COMPLETED_ORDERS: 'completed_orders',
  ITEM_CATEGORY:'item_category',
  CATEGORY_CREATED_BY_VENDOR: 'category_created_by_vendor',
  DELIVERY_PARTNER:'delivery_partner',
  OFFER_BANNER: 'offer_banner',
  ITEM:"item",
  SUPPORT_TEAM: 'support_team',
  
};

export const COLUMNS = {
  VENDOR: {
    ID: "v_id",
    V_NAME: "v_name",
    U_ID:"u_id",
    WARNING:"warning",
    BLOCKED:"blocked",
    SHOP_NAME: "shop_name",
    CREATED_AT: "created_at",
    UPADATED_AT: "updated_at",
    BANNER_URL: "banner_url",
    SHIFT1_OPENING_TIME: "shift1_opening_time",
    SHIFT1_CLOSING_TIME: "shift1_closing_time",
    SHIFT2_OPENING_TIME: "shift2_opening_time",
    SHIFT2_CLOSING_TIME: "shift2_closing_time",
    DISCOUNT: "discount_available",
    LATITUDE: "latitude",
    LONGITUDE: "longitude",
    REQUEST_STATUS: "request_status",
    REJECTION_REASON: "rejection_reason",
    VIDEO_URL: "video_url",
    RATING: "rating",
    EXPECTED_DELIVERY_TIME:"expected_dt_ms",
    APPROVED_BY:"approved_by",
    STATUS:"status",
    NOTE_FROM_VENDOR: "note_from_vendor",
    PAYMENT_URL: "payment_url",
    RATING_COUNT: "rating_count",
    CITY:"city",
    STATE:"state",
    STREET:"street",
    PINCODE:"pincode",
    MOBILE: "mobile_number",
    AVAILABLE: "available",
    CUISINES: "cuisines_available",
    LOCATION: "location",
  },
  DELIVERY_ADDRESS: {
    ADDRESS_ID: "address_id",
    CREATED_AT:"created_at",
    UPDATED_AT:"updated_at",
    U_ID:"u_id",
    LAT: "lat",
    LONG: "long",
    IS_SELECTED: "is_selected",
    H_NO: "h_no",
    LANDMARK:"landmark",
    CONTACT_NO:"contact_no",
    ADDITIONAL_DETAILS:"additional_details",
    ADDRESS_TYPE: "address_type",
    SEARCH_TEXT: "search_text",
  },
   USER: {
    ID: "user_id",
    CREATED_AT: "created_at",
    NAME: "name",
    MOBILE: "mobile_number",
    BLOCKED: "blocked",
    INCOME_RANGE: "income_range",
    UPDATED_AT: "updated_at",
    WALLET_BALANCE: "wallet_balance",
    WARNING: "warning",
    REFERRED_BY: "referred_by",
    RATING: "rating",
    DP_URL: "dp_url",
    PROFESSION: "profession",
    ROLE: "role",
  },
    SUPPORT_TEAM: {
    USER_ID: "user_id",
    STATUS: "status"
  }
};
